/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.oop.BargainBin;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;


/**
 *
 * @author binup
 */
public class Temp extends java.awt.Frame {

    /**
     * Creates new form MainPageUI
     */
    public Temp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPage = new javax.swing.JPanel();
        Tabs = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        MarketPanel = new javax.swing.JPanel();
        CartBtn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        Tabs.setToolTipText("");

        HomePanel.setName(""); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        Tabs.addTab("Home", HomePanel);

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        Tabs.addTab("Profile", ProfilePanel);

        javax.swing.GroupLayout MarketPanelLayout = new javax.swing.GroupLayout(MarketPanel);
        MarketPanel.setLayout(MarketPanelLayout);
        MarketPanelLayout.setHorizontalGroup(
            MarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        MarketPanelLayout.setVerticalGroup(
            MarketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        Tabs.addTab("Market", MarketPanel);

        MainPage.add(Tabs);

        CartBtn.setText("Cart");
        CartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBtnActionPerformed(evt);
            }
        });
        MainPage.add(CartBtn);

        add(MainPage);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void CartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    //step 1 bargain bin single instance made in main
    //login view and account model constructed.
    //acount controller constructed pass login vie and account model.
    /**
     * when user registers or logs in
     * account controller will populate account model
     * account controller will create instance of account class seller or customer
     * account controller will temp make copy or main frame
     * account controller will call parent of login view panel and remove it
     * then the specific version of account type class seller or buyer method strategy pattern
     * Stretegy pattern will make the panels/views for each account type and do  mainframe.add()
     * 
     */
    
    
    
    public static void main(String args[]) {
        Temp main = new Temp();
        
        LoginRegisterView login = null;
        System.out.println("login added");
        login = new LoginRegisterView();
        JTabbedPane loginPanel = login.getTabs();
        main.setLayout(new BorderLayout());
        System.out.println(login);
        main.add(loginPanel);
        
        
        //main.pack();
        
        System.out.println(loginPanel.getParent());
        main.setVisible(true);
        //main.setBounds(0, 0, main.getWidth(), main.getHeight() - main.Tabs.getHeight());
        main.MainPage.remove(0);
        
        
        System.out.println(main);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartBtn;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel MainPage;
    private javax.swing.JPanel MarketPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JTabbedPane Tabs;
    // End of variables declaration//GEN-END:variables
}
